/*
 * ChatBox.java
 *
 * Created on __DATE__, __TIME__
 */

package client.gui;

import java.sql.Date;
import client.helper.NetAccessHelper;
import entity.Contact;
import entity.NotifyObject;
import entity.RequestObject;
import entity.ChatInfo;

/**
 *
 * @author  __USER__
 */
public class ChatBox extends javax.swing.JFrame {
	//private static final Object ChatInfo = null;
	/** Creates new form ChatBox */
	public ChatBox(Contact bfContact, Contact gfContact) {
		initComponents();
		this.bfContact = bfContact;
		this.gfContact = gfContact;
		setDefaultCloseOperation(HIDE_ON_CLOSE);

		setTitle(bfContact.getUname() + "is chatting with"
				+ gfContact.getUname());
	}

	/***************************26new***************************************/

	public void appendMsg(String msg) {
		this.txtHist.append(msg);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtHist = new javax.swing.JTextArea();
		txtChat = new javax.swing.JTextField();
		btnSend = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		txtHist.setColumns(20);
		txtHist.setRows(5);
		jScrollPane1.setViewportView(txtHist);

		txtChat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtChatActionPerformed(evt);
			}
		});

		btnSend.setText("send");
		btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnSendMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(91, 91, 91)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				txtChat,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				476,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				btnSend,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																584,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(179, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												281,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																txtChat,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																47,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btnSend,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																48,
																Short.MAX_VALUE))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(71, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**************************************************************/
	//mouse Click and Open ChatBox
	private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

		ChatInfo chatInfo = new ChatInfo();
		chatInfo.setSenderId(bfContact.getUid());
		chatInfo.setReceiverid(gfContact.getUid());

		Date now = new Date(System.currentTimeMillis());
		String sentTime = now.toString();

		/**************************************************************/
		chatInfo.setSendTime(sentTime);
		System.out.println(sentTime);

		String content = sentTime + "\n" + bfContact.getUname() + "  Said to"
				+ gfContact.getUid() + ":\n" + txtChat.getText() + "\n";

		chatInfo.setContent(content);
		txtChat.setText("");
		txtHist.append(content);

		/////////////////////////////////////14:40?????????????????????????????
		//
		if (gfContact.getOnline() != 1) {
			RequestObject requestObject = new RequestObject(
					RequestObject.OFF_CHAT, chatInfo);
			NetAccessHelper.sendRequest(requestObject);
		}

		//online
		//define notifyObject
		//new notifyObject
		//add
		else {
			System.out.println("2222");
			NotifyObject notifyObject = new NotifyObject();
			notifyObject.setNotifyType(NotifyObject.TEXT_MSG);
			notifyObject.setNotifyBody(chatInfo);
			notifyObject.setSourceIp(bfContact.getPeerIp());
			notifyObject.setDestIp(gfContact.getPeerIp());
			notifyObject.setSourcePort(bfContact.getPeerPort());
			notifyObject.setDestPort(gfContact.getPeerPort());
			NetAccessHelper.notify(notifyObject);

//			notifyObject.setNotifyBody(content);
		}
		/////////////////////////////////////////////////////////////////////

	}

	private void txtChatActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new ChatBox().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnSend;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField txtChat;
	private javax.swing.JTextArea txtHist;
	// End of variables declaration//GEN-END:variables
	private Contact bfContact, gfContact;
}
