/*
 * LogForm.java
 *
 * Created on __DATE__, __TIME__
 */

package client.gui;

import java.net.InetAddress;

import javax.swing.JOptionPane;
import client.helper.NetAccessHelper;
import client.listener.EventListenerThread;
import entity.Loginfo;
import entity.PeerInfo;
import entity.RequestObject;
import entity.ResponseObject;

/**
 *
 * @author  __USER__
 */
public class LogForm extends javax.swing.JFrame {

	/** Creates new form LogForm */
	public LogForm() {
		initComponents();

		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		pass = new javax.swing.JPasswordField();
		txtUID = new javax.swing.JTextField();
		Login = new javax.swing.JButton();
		Register = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("uid");

		jLabel2.setText("password");

	

		Login.setText("Login");
		Login.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				LoginMouseClicked(evt);
			}
		});

		Register.setText("Register");
		Register.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				RegisterMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				95,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				pass,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				286,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				86,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				txtUID,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				286,
																				Short.MAX_VALUE)))
										.addGap(86, 86, 86))
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addGap(52, 52, 52).addComponent(Login)
										.addGap(98, 98, 98)
										.addComponent(Register)
										.addContainerGap(186, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(70, 70, 70)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																36,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txtUID,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																31,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(56, 56, 56)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																42,
																Short.MAX_VALUE)
														.addComponent(
																pass,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(57, 57, 57)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(Login)
														.addComponent(Register))
										.addGap(44, 44, 44)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(64, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void LoginMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		
		Loginfo loginfo = new Loginfo();
		loginfo.setPassword(new String(pass.getPassword()));
		/***************setUid*******************/
		int uid = Integer.parseInt(txtUID.getText());		
		loginfo.setUid(uid);
		RequestObject requestObject = new RequestObject(RequestObject.LOGIN_REQ, loginfo);
		ResponseObject responseObject = NetAccessHelper
				.sendRequest(requestObject);
		if (responseObject.getResType() == ResponseObject.LOGIN_FAILED) {
			JOptionPane.showMessageDialog(this, responseObject.getResBody());

		} else /////*********************26_14:00*****************************/////
			{		
			EventListenerThread peerListenerThread=new EventListenerThread();
			peerListenerThread.start();
			
			try {
				Thread.sleep(2000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			InetAddress peerIp=peerListenerThread.getPeerIp();
			int peerPort=peerListenerThread.getPeerPort();
			
			//requestObject
			
			PeerInfo peerInfo=new PeerInfo();
			peerInfo.setPeerIp(peerIp);
			peerInfo.setPeerPort(peerPort);
			peerInfo.setUid(uid);
			
			requestObject=new RequestObject(RequestObject.REG_PEER_REQ, peerInfo);
			NetAccessHelper.sendRequest(requestObject);
//////////////////////////////////////////////////////////////////////
			MainForm mainForm = new MainForm(uid);
			mainForm.setVisible(true);
			
			mainForm.refreshContacts(true);
			mainForm.initOfflineMsgs();
			mainForm.startTimer();
			dispose();
		}
	}
	private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		RegForm regForm = new RegForm();
		regForm.setVisible(true);
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LogForm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton Login;
	private javax.swing.JButton Register;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField pass;
	private javax.swing.JTextField txtUID;
	// End of variables declaration//GEN-END:variables

}