/*
 * RegForm.java
 *
 * Created on __DATE__, __TIME__
 */

package client.gui;

import javax.swing.JOptionPane;

import client.helper.NetAccessHelper;
import entity.RegInfo;
import entity.RequestObject;
import entity.ResponseObject;

/**
 * 
 * @author __USER__
 */
public class RegForm extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// private static final Object regInfo = null;

	/** Creates new form RegForm */
	public RegForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		nametxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		agetxt = new javax.swing.JTextField();
		emailtxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		btnRegister = new javax.swing.JButton();
		btnReset = new javax.swing.JButton();
		password = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Name");

		jLabel2.setText("Email");

		jLabel3.setText("Age");

		jLabel4.setText("password");

		btnRegister.setText("Register");
		btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnRegisterMouseClicked(evt);
			}
		});

		btnReset.setText("Reset");
		btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnResetMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(54, 54, 54)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								67,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel2))
																		.addGap(8,
																				8,
																				8))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												nametxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												205,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(48,
																												48,
																												48)
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												46,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(15,
																												15,
																												15)
																										.addComponent(
																												agetxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												126,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								emailtxt,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								440,
																								Short.MAX_VALUE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												btnRegister)
																										.addGap(170,
																												170,
																												170)
																										.addComponent(
																												btnReset,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												89,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(88,
																				88,
																				88))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				password,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				513,
																				Short.MAX_VALUE)
																		.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																32,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																agetxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																nametxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(33, 33, 33)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																emailtxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																41,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(40, 40, 40)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																password,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																40,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btnReset,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																40,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btnRegister,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents
	
	
	
	// RegisterMouseClick
	private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

		RegInfo regInfo = new RegInfo();
		regInfo.setUname(this.nametxt.getText());
		regInfo.setEmail(this.emailtxt.getText());
		int age = Integer.parseInt(this.agetxt.getText());
		regInfo.setAge(age);
		String passString = new String(this.password.getPassword());
		regInfo.setPassword(passString);
		// JOptionPane
		
		// .showMessageDialog(this, regInfo);
		System.out.println(regInfo);

		// RequestObject
		RequestObject requestObject = new RequestObject(RequestObject.REG_REQ,
				regInfo);
		//
		ResponseObject responseObject = NetAccessHelper
				.sendRequest(requestObject);

		JOptionPane.showMessageDialog(this,(String) responseObject.getResBody());
	}
	
	private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		this.agetxt.setText("");
		this.emailtxt.setText("");
		this.nametxt.setText("");
		this.password.setText("");
	}


	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegForm().setVisible(true);
			}
		});
	}


	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField agetxt;
	private javax.swing.JButton btnReset;
	private javax.swing.JTextField emailtxt;
	private javax.swing.JButton btnRegister;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField nametxt;
	private javax.swing.JPasswordField password;
	// End of variables declaration//GEN-END:variables

}